# Generated by Django 4.2.7 on 2024-04-19 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrecord',
            name='time_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderrecord',
            name='number_of_cases',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderrecord',
            name='time_finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderrecord',
            name='time_started',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='storetimes',
            name='hour_due',
            field=models.IntegerField(),
        ),
    ]
