# Generated by Django 4.2.7 on 2024-04-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_orderrecord_time_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrecord',
            name='time_started',
            field=models.DateTimeField(),
        ),
    ]
